import { EmailIcon, ExternalLinkIcon } from "@chakra-ui/icons";
import { Grid, GridItem, Link, Text } from "@chakra-ui/react";
import { graphql, useStaticQuery } from "gatsby";
import React from "react";
import { expandNewlines } from "../utils/util";

function About() {
  const data = useStaticQuery(graphql`
    {
      allSite {
        nodes {
          siteMetadata {
            author {
              email
              name
            }
          }
        }
      }
      aboutEtsyStore {
        id
        data {
          shop_id
          status
          story_headline
          story_leading_paragraph
          story
          url
        }
      }
    }
  `)

  const aboutStore = data?.aboutEtsyStore?.data[0]
  const aboutMe = data?.allSite?.nodes[0].siteMetadata.author
  const emailLink = `mailto:${aboutMe.email}`

  return (
    <Grid templateColumns="repeat(3, 1fr)" gap={4} >
      <GridItem colSpan={1}>
        <Text fontSize="xl"><div dangerouslySetInnerHTML={{ __html: expandNewlines(aboutStore.story_headline) }}></div></Text>
      </GridItem>
      <GridItem colSpan={2}>
        <Text fontSize="sm"><div dangerouslySetInnerHTML={{ __html: expandNewlines(aboutStore.story_leading_paragraph) }}></div></Text>
        <Text><div dangerouslySetInnerHTML={{ __html: expandNewlines(aboutStore.story) }}></div></Text>
      </GridItem>

      <GridItem colSpan={1}>
        <Text fontSize="xl">Contact us</Text>
      </GridItem>
      <GridItem colSpan={2}>
        <EmailIcon />  <Link href={emailLink} isExternal>{aboutMe.email}</Link>
      </GridItem>

      <GridItem colSpan={1}>
        <Text fontSize="xl">This website</Text>
      </GridItem>
      <GridItem colSpan={2}>
        <Text>Built using <Link href="https://www.gatsbyjs.com/" isExternal>GatsbyJS <ExternalLinkIcon /></Link>
          {` `}and <Link href="https://chakra-ui.com/">Chakra UI <ExternalLinkIcon /></Link>.
        All pages are generated by calling the Etsy store API directly.</Text>
      </GridItem>
      <GridItem colStart={2} colSpan={2}>
        <Text>Including, surprisingly, this one.</Text>
      </GridItem>
    </Grid>
  )
}

export default About
